---
title: "Homework Session 3: Solving issues"
author:
  - name: Meho Porobic
    email: mporobic10@gmail.com
date: last-modified
format: gfm
---

Make one or more pull request to <https://github.com/linushof/BayesIntro24> solving the specified [issues](https://github.com/linushof/BayesIntro24/issues).

```{r}
#load packages
library(tidyverse)
```

```{r}
set.seed(14)
x <- rnorm(1000, 100, 20)
y <- rnorm(1000, 90, 20)
dat <- data.frame(x, y)
```

```{r}
head(dat, 10) %>%
  kable(digits = 2)
```

```{r}
dat_long <- data.frame(group = c(rep("x", 1000), rep("y", 1000)), 
                       val = c(x, y))
```

```{r}
head(dat_long, 10) %>%
  kable(digits = 2)
```

```{r}
dat_long %>%
  ggplot(
    aes(x = val, fill = group)
    ) +
  geom_histogram(
    position = "identity",
    alpha = .5,
    bins = 30,
    binwidth = 2,
    na.rm = TRUE
    ) +
  scale_fill_manual(values=c("#69b3a2", "#404080")) +
  xlim(0, 200) +
  ylim(0, 50) +
  labs(
    title = "Better Plot",
    fill = "Groups",
    x = "Values",
    y = "Counts"
    )
```

```{r}
dat$diff <- dat$x - dat$y

dat %>%
  ggplot(aes(x = diff)) +
  geom_histogram(
    fill = "#69b3a2",
    bins = 30,
    binwidth = 2,
    na.rm = TRUE
    ) +
  xlim(-100,100) +
  ylim(0, 50) +
  labs(
    title = "Difference Plot",
    x = "Differences",
    y = "Counts"
    )
```
